services:
  # Service names
  app:
    # Dockerfile location
    container_name: 'lang_chain_app'
    build:
      context: ..
      dockerfile: ./.devcontainer/images/python/Dockerfile
    tty: true
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env.development
    volumes:
      - ..:/workspace
    # default command so things don't shut down after the process ends.
    ports:
      - 8000:8000
    expose:
      - '8000'
